add publication citation
Sanofi-Public/spatialone-pipeline pull request #11
Opened 2024-10-01 15:12 UTC by mathewsunaal

2024-10-01 15:18 UTC, AlbertPlaPlanas requested changes

2024-10-01 15:18 UTC, AlbertPlaPlanas commented on README.md
> +
Add a specific section about citation at the end of the readme where you explicitly request the user to cite us if they use the software. A few exmaples:
<img width="884" alt="image" src="https://github.com/user-attachments/assets/c82f0255-e90d-42c4-90c4-701fd1b56346">
<img width="941" alt="image" src="https://github.com/user-attachments/assets/13fde5c0-566e-41ca-9f8e-889563c920e6">
<img width="965" alt="image" src="https://github.com/user-attachments/assets/dd142a35-08fa-4c8c-98dd-c9bbe04213ec">

2024-10-01 15:25 UTC, mathewsunaal commented on README.md
> +
Thanks Albert, will do.

2024-10-04 13:19 UTC, blankachamradova approved these changes

2024-10-07 14:54 UTC, AlbertPlaPlanas approved these changes

2024-10-08 12:35 UTC, merged